// RETAIL — kirana, petrol pump, mall fashion, jewellery, mobile shop, supermarket cashier
import { S, mk, type WorkedExample } from './_shared';

const medicalShop = () => mk({
  role: 'Retail chemist (medical-shop owner-pharmacist)',
  context: 'A neighbourhood pharmacy; doctor prescriptions + OTC + monthly-credit chronic patients; Schedule-H drugs',
  outputName: 'a prescription / medicine sale dispensed and billed',
  officialVersion: 'Read prescription → check stock → dispense exact drug → record Schedule-H → bill → advise dosage → take payment.',
  instanceAnchor: 'an evening walk-in with a hand-written prescription + a chronic regular on credit',
  trigger: 'Customer hands over a prescription or asks for a medicine by name',
  steps: [
    S(1, { action: 'Decipher the doctor\'s handwriting — drug, strength, frequency', tool: 'Eye + experience', inputSource: 'A client / customer', timeMins: 2, frequency: 'many-times-a-day', needsJudgment: true, isPainful: true, notes: 'Mis-reading a scrawled strength is the scariest error; sometimes I phone the clinic to confirm.' }),
    S(2, { action: 'Decide exact brand vs generic substitute by stock + price + what suits', tool: 'Mental formulary', frequency: 'many-times-a-day', needsJudgment: true }),
    S(3, { action: 'Locate from racks / drawers, check batch + expiry', tool: 'Racks + boxes', timeMins: 2, frequency: 'many-times-a-day', frictionTags: ['lookup', 'movement'] }),
    S(4, { action: 'Enter Schedule-H sale in the register (drug, qty, prescriber)', tool: 'Bound register', frequency: 'many-times-a-day', frictionTags: ['manual-transfer', 'approval'], notes: 'Statutory log, hand-written separate from the bill — pure double entry.' }),
    S(5, { action: 'Bill on POS; add OTC items asked for', tool: 'Billing software', timeMins: 2, frequency: 'many-times-a-day' }),
    S(6, { action: 'Mark a chronic regular\'s monthly credit in a side ledger', tool: 'Credit ledger', isShadow: true, frequency: 'daily', needsJudgment: true, notes: 'BP/diabetes regulars buy monthly and settle on pension day — a trust account the POS does not hold.' }),
    S(7, { action: 'Advise dosage / timing / interactions in plain Tamil', tool: 'Voice', outputDestination: 'A client / customer', frequency: 'many-times-a-day', needsJudgment: true }),
    S(8, { action: 'Note low / near-expiry stock to reorder from distributor', tool: 'Notebook + distributor app', inputSource: 'My own notes', timeMins: 15, frequency: 'daily', isShadow: true, frictionTags: ['lookup'] }),
  ],
  handoffs: [
    { direction: 'wait-on', who: 'Pharma distributor', what: 'next-day stock replenishment', typicalDelay: 'daily van' },
    { direction: 'wait-on', who: 'Prescribing clinic', what: 'clarification on an unclear prescription', typicalDelay: 'minutes by phone' },
  ],
  exceptions: [
    { trigger: 'Prescribed brand out of stock', whatYouDo: 'Offer same-salt substitute with the patient\'s ok; note to reorder', howOften: 'daily' },
    { trigger: 'Near-expiry stock unsold', whatYouDo: 'Return to distributor before cut-off date; track expiry rack weekly', howOften: 'monthly' },
  ],
});

const hardwareStore = () => mk({
  role: 'Hardware / building-materials shop owner',
  context: 'Sells cement, pipes, paint, electricals, fittings; walk-ins + contractor credit (khata) accounts; auto delivery',
  outputName: 'a contractor / customer materials order fulfilled and billed',
  officialVersion: 'Take order → check stock → advise correct spec → bill or post to khata → arrange delivery → settle monthly for credit accounts.',
  instanceAnchor: 'a mid-morning with a contractor calling in a site list while walk-ins wait',
  trigger: 'Contractor phones a list / a customer walks in with a fitting to match',
  steps: [
    S(1, { action: 'Take the order — often a phoned list or a sample part to match', tool: 'Phone + counter', inputSource: 'A client / customer', timeMins: 4, frequency: 'many-times-a-day', frictionTags: ['lookup'], needsJudgment: true, notes: '"½-inch elbow, the good brand" — translating loose contractor-speak into exact SKUs.' }),
    S(2, { action: 'Hunt stock across crowded racks + loft + godown', tool: 'Racks + godown', timeMins: 5, frequency: 'many-times-a-day', frictionTags: ['lookup', 'movement'] }),
    S(3, { action: 'Advise grade / spec — which pipe class, cement grade, wire gauge', tool: 'Experience', frequency: 'many-times-a-day', needsJudgment: true }),
    S(4, { action: 'Post to the contractor\'s khata or bill cash; quote price by relationship', tool: 'Khata ledger + bill book', isShadow: true, frequency: 'many-times-a-day', needsJudgment: true, notes: 'Regular contractors get a remembered rate + running credit — the price isn\'t on a tag.' }),
    S(5, { action: 'Load + dispatch by auto / tempo to the site', tool: 'Auto + loader', outputDestination: 'A client / customer', timeMins: 15, frequency: 'daily', frictionTags: ['movement', 'chasing'] }),
    S(6, { action: 'Reorder fast-movers from dealers as stock dips', tool: 'Phone + dealer', inputSource: 'My own notes', frequency: 'daily', frictionTags: ['lookup'] }),
    S(7, { action: 'Month-end: reconcile each contractor khata, chase dues, settle returns', tool: 'Ledger + calculator', inputSource: 'My own notes', timeMins: 90, frequency: 'monthly', frictionTags: ['manual-transfer', 'chasing'], isPainful: true, notes: 'Untangling a month of credit, partial payments and site returns is the dreaded chore.' }),
  ],
  handoffs: [
    { direction: 'wait-on', who: 'Cement / pipe dealers', what: 'stock replenishment + credit period', typicalDelay: '1–3 days' },
    { direction: 'hand-to', who: 'Site supervisor', what: 'delivered materials + delivery note', typicalDelay: 'same day' },
  ],
  exceptions: [
    { trigger: 'Wrong item delivered to site', whatYouDo: 'Send the right one with next auto, take back the wrong, adjust khata', howOften: 'weekly' },
    { trigger: 'Contractor disputes month-end total', whatYouDo: 'Walk the khata page entry by entry; concede small gaps to keep the account', howOften: 'monthly' },
  ],
});

const sareeShowroom = () => mk({
  role: 'Saree showroom sales associate',
  context: 'A large TN textile showroom (Pothys / RmKV-style); wedding-season shoppers; sectioned floors; separate billing + packing counters',
  outputName: 'a customer\'s saree selection closed and billed',
  officialVersion: 'Greet → understand occasion + budget → show options → finalise → token to billing → pay → collect at packing.',
  instanceAnchor: 'a wedding family buying for multiple relatives on a Saturday',
  trigger: 'A family sits at the counter and names the occasion',
  steps: [
    S(1, { action: 'Read the occasion, budget, who it\'s for, the unspoken status cues', tool: 'Conversation', inputSource: 'A client / customer', timeMins: 6, frequency: 'many-times-a-day', needsJudgment: true, notes: '"Something for the bride\'s mother" carries colour, price and prestige rules I judge on the fly.' }),
    S(2, { action: 'Pull saree after saree, drape, spread on the counter to show', tool: 'Stock shelves + hands', timeMins: 25, frequency: 'many-times-a-day', frictionTags: ['movement'], isPainful: true, notes: 'Twenty pulled for two sold — the physical pulling + the no-buy risk is the draining part.' }),
    S(3, { action: 'Suggest matching blouse, combinations, what pairs for the function', tool: 'Eye + experience', frequency: 'many-times-a-day', needsJudgment: true }),
    S(4, { action: 'Park likely picks aside, track each family member\'s shortlist', tool: 'Counter + memory', isShadow: true, frequency: 'many-times-a-day', needsJudgment: true, notes: 'Whose pile is whose, what\'s "maybe" vs "yes" — held in head across a long sit.' }),
    S(5, { action: 'Write selection slip, send customer + slip to billing counter', tool: 'Slip', outputDestination: 'Another team', frequency: 'many-times-a-day', frictionTags: ['manual-transfer', 'wait'] }),
    S(6, { action: 'Customer pays at billing, collects at packing — separate queues', tool: 'Billing + packing counters', frequency: 'many-times-a-day', frictionTags: ['wait'] }),
    S(7, { action: 'Refold + restock every pulled-but-unsold saree to its rack', tool: 'Hands', timeMins: 15, frequency: 'many-times-a-day', frictionTags: ['movement', 'rework'], isShadow: true, notes: 'Invisible reset work after each customer — counts for nothing on the sales sheet.' }),
  ],
  handoffs: [
    { direction: 'hand-to', who: 'Billing counter', what: 'selection slip for invoicing', typicalDelay: 'queue-dependent' },
    { direction: 'hand-to', who: 'Packing counter', what: 'paid items for packing + handover', typicalDelay: 'queue-dependent' },
  ],
  exceptions: [
    { trigger: 'Customer leaves to "think" after a long showing', whatYouDo: 'Note the shortlist, restock, hope they return; no loss recorded but time gone', howOften: 'daily' },
    { trigger: 'Desired design out of stock in the colour', whatYouDo: 'Check other branch / godown, offer to hold or order, take a number', howOften: 'weekly' },
  ],
});

const kiranaStore = () => mk({
  role: 'Kirana store owner (neighbourhood grocery)',
  context: 'A single-family kirana in a Chennai residential lane; cash, UPI and credit (paavi/notebook); compete with Big Basket / Zepto',
  outputName: 'a customer served and the day-book balanced',
  officialVersion: 'Customer asks → fetch goods → bill on calculator → take payment → log if credit → restock at day end.',
  instanceAnchor: 'an evening regular doing the weekly grocery, last Sunday',
  trigger: 'A customer walks in or shouts an order from the doorway',
  steps: [
    S(1, { action: 'Take the order — verbal list, sometimes a phone screenshot', tool: 'Voice / phone', inputSource: 'A client / customer', timeMins: 3, frequency: 'many-times-a-day', needsJudgment: true, notes: 'Regulars say "the usual" — I know what that is.' }),
    S(2, { action: 'Fetch each item across shelves and the back godown', tool: 'Hands + memory of shelf layout', timeMins: 8, frequency: 'many-times-a-day', frictionTags: ['movement', 'lookup'] }),
    S(3, { action: 'Weigh loose items (dal, atta, oil) on the electronic scale', tool: 'Digital scale', timeMins: 4, frequency: 'many-times-a-day' }),
    S(4, { action: 'Calculate the bill — sometimes on Vyapar app, sometimes on paper, sometimes in my head', tool: 'Vyapar / calculator / mental math', outputWhat: 'a total', timeMins: 3, frequency: 'many-times-a-day', needsJudgment: true, isShadow: true, notes: 'Vyapar takes too long for small bills; I switch based on bill size.' }),
    S(5, { action: 'Take payment — UPI QR, cash, or "write in the book"', tool: 'UPI QR + cash drawer + credit notebook', frequency: 'many-times-a-day', needsJudgment: true, notes: 'Credit only for trusted families. The book is my judgment.' }),
    S(6, { action: 'Pack into a carry bag, sometimes deliver to upstairs flats myself', tool: 'Carry bags + lift', outputDestination: 'A client / customer', timeMins: 4, frequency: 'many-times-a-day', frictionTags: ['movement'] }),
    S(7, { action: 'Note items running low for tomorrow\'s order to the distributor', tool: 'Pencil + reorder slip', inputSource: 'My own notes', timeMins: 2, frequency: 'many-times-a-day', isShadow: true }),
    S(8, { action: 'Tally cash, UPI screenshots and the credit book at day end', tool: 'Cash drawer + UPI history + notebook', inputSource: 'My own notes', timeMins: 25, frequency: 'daily', frictionTags: ['manual-transfer'], isPainful: true, notes: 'Three sources, one number — and it has to match every night.' }),
    S(9, { action: 'WhatsApp distributor for tomorrow\'s order', tool: 'WhatsApp', outputDestination: 'Distributor', timeMins: 8, frequency: 'daily', frictionTags: ['chasing'] }),
  ],
  handoffs: [
    { direction: 'wait-on', who: 'Distributor / wholesaler', what: 'morning replenishment delivery', typicalDelay: 'next morning' },
    { direction: 'wait-on', who: 'Credit customers', what: 'monthly settlement', typicalDelay: 'often runs 1–2 months' },
  ],
  exceptions: [
    { trigger: 'Online price war — Zepto undercutting on milk', whatYouDo: 'Match on essentials, hold margin on add-ons, lean on relationship value', howOften: 'continuously' },
    { trigger: 'Credit customer goes overdue past my limit', whatYouDo: 'Polite reminder via the husband / sometimes the son, stop further credit until cleared', howOften: 'few customers a year' },
  ],
});

const petrolPump = () => mk({
  role: 'Petrol pump cashier-attendant (shift in-charge)',
  context: 'A 4-nozzle HPCL / IOCL outlet on a Chennai arterial road; cash, card, UPI, fleet cards',
  outputName: 'a shift closed with cash, dip and meter readings reconciled',
  officialVersion: 'Opening totaliser → fill per customer → take payment → close totaliser → physical dip → reconcile cash + electronic vs sold litres → cash to bank deposit.',
  instanceAnchor: 'the morning rush shift last Friday',
  trigger: 'Shift handover happens at 6 AM — previous attendant gives keys',
  steps: [
    S(1, { action: 'Record opening totaliser reading for each nozzle in the daily sheet', tool: 'Nozzle totaliser + paper register', outputWhat: 'opening reading', timeMins: 10, frequency: 'daily', frictionTags: ['manual-transfer'] }),
    S(2, { action: 'Take the physical tank dip with the dip-rod, note the level', tool: 'Dip rod + chart', inputSource: 'A system / report', outputWhat: 'opening stock', timeMins: 15, frequency: 'daily', frictionTags: ['movement'], needsJudgment: true }),
    S(3, { action: 'Customer arrives — ask amount or full tank, ZERO display, dispense', tool: 'Dispenser + voice', inputSource: 'A client / customer', timeMins: 2, frequency: 'many-times-a-day' }),
    S(4, { action: 'Take payment — UPI scan, card swipe, cash, or fleet card', tool: 'UPI QR + EDC machine + cash bag', timeMins: 2, frequency: 'many-times-a-day', frictionTags: ['wait'], notes: 'Card terminal flaky at peak — sometimes process twice by mistake.' }),
    S(5, { action: 'For company / fleet bills, write the slip with vehicle number and signature', tool: 'Slip book', timeMins: 3, frequency: 'many-times-a-day', frictionTags: ['manual-transfer'] }),
    S(6, { action: 'Handle "₹100 only" customer who really wants ₹103 — judge / refund', tool: 'Voice + petty cash', needsJudgment: true, frequency: 'many-times-a-day', notes: 'These small disputes are exhausting; I have a routine.' }),
    S(7, { action: 'At noon and shift end, take the dispenser reading + cash + card sum', tool: 'Totaliser + cash count + EDC report', inputSource: 'A system / report', timeMins: 25, frequency: 'daily', frictionTags: ['manual-transfer', 'lookup'], isPainful: true, notes: 'Reading minus opening = sold litres; sold litres × price = expected money. Must match.' }),
    S(8, { action: 'If short, retrace — wrong-product fill, leak, fleet slip missing, denomination error', tool: 'Notebook + memory', inputSource: 'My own notes', timeMins: 20, frequency: 'daily', needsJudgment: true, isShadow: true, frictionTags: ['rework'], notes: 'Short = my pocket. Spend the time to find it.' }),
    S(9, { action: 'Hand over cash + reading + UPI / EDC printouts to the manager', tool: 'Cash bag + sheets', outputDestination: 'Outlet manager', timeMins: 10, frequency: 'daily', frictionTags: ['approval'] }),
  ],
  handoffs: [
    { direction: 'wait-on', who: 'Outlet manager', what: 'cash collection and sign-off', typicalDelay: 'shift end' },
    { direction: 'hand-to', who: 'Next shift attendant', what: 'closing readings = their opening', typicalDelay: 'immediate' },
  ],
  exceptions: [
    { trigger: 'Wrong-product fill (petrol into a diesel vehicle)', whatYouDo: 'Stop pump, escalate to manager, customer cost-share negotiation, paperwork', howOften: 'a few times a year' },
    { trigger: 'Card terminal double-charges', whatYouDo: 'Print slip, return amount to customer in cash, raise dispute with bank', howOften: 'monthly' },
  ],
});

const mallFashion = () => mk({
  role: 'Floor sales associate (mall fashion brand)',
  context: 'A mid-tier fashion brand outlet in a Chennai mall; commission on monthly target',
  outputName: 'a customer billed and walking out with a bag',
  officialVersion: 'Greet → understand need → suggest → trial → close → POS → loyalty enrolment → exit greeting.',
  instanceAnchor: 'a Sunday afternoon customer who came in for a shirt and left with three',
  trigger: 'A customer walks in through the entry sensor',
  steps: [
    S(1, { action: 'Greet at door, read the customer — alone, family, hurried, browsing', tool: 'Voice + eyes', inputSource: 'A client / customer', timeMins: 2, frequency: 'many-times-a-day', needsJudgment: true, notes: 'Pushy greeting = lost sale. The read is the skill.' }),
    S(2, { action: 'Ask the occasion / need, suggest 2–3 pieces from the right rack', tool: 'My memory of stock + voice', timeMins: 5, frequency: 'many-times-a-day', isShadow: true, notes: 'POS shows stock by SKU; I track new arrivals by what I personally hung up that morning.' }),
    S(3, { action: 'Walk customer to the trial room, hand pieces, suggest a size up / down', tool: 'Trial room', frequency: 'many-times-a-day', frictionTags: ['movement'] }),
    S(4, { action: 'Outside trial room — wait, judge mood when they come out', tool: 'Voice + mirror', frequency: 'many-times-a-day', frictionTags: ['wait'], needsJudgment: true }),
    S(5, { action: 'Bring add-ons — belt, accessory, matching kurta — to bump basket size', tool: 'Hands + memory', timeMins: 4, frequency: 'many-times-a-day', needsJudgment: true, notes: 'My commission is on basket, not footfall.' }),
    S(6, { action: 'Close — read the cue ("how much?"), do not over-talk, walk to POS', tool: 'Voice', frequency: 'many-times-a-day', needsJudgment: true, isPainful: true, notes: 'Bad close kills good show. Quiet confidence.' }),
    S(7, { action: 'Bill on POS, push loyalty enrolment via OTP, offer the next-buy voucher', tool: 'POS + loyalty app', outputDestination: 'POS', timeMins: 4, frequency: 'many-times-a-day', frictionTags: ['wait'], notes: 'Loyalty target hits my dashboard too.' }),
    S(8, { action: 'Pack into branded carry bag, escort to door, suggest the new collection next week', tool: 'Carry bag + voice', outputDestination: 'A client / customer', timeMins: 2, frequency: 'many-times-a-day' }),
    S(9, { action: 'Log lost-sale reason in my own notebook — size out, price, style', tool: 'Personal pocket notebook', inputSource: 'My own notes', frequency: 'daily', isShadow: true, notes: 'Brand HQ asks for reasons in a weekly form — I copy from my notebook.' }),
  ],
  handoffs: [
    { direction: 'wait-on', who: 'Stockroom assistant', what: 'a size from back', typicalDelay: 'minutes' },
    { direction: 'hand-to', who: 'Cashier (if separate)', what: 'customer + items to POS', typicalDelay: 'seconds' },
  ],
  exceptions: [
    { trigger: 'Size not in stock', whatYouDo: 'Suggest alternate cut, offer to ship from another store, take number to call when restocked', howOften: 'daily' },
    { trigger: 'Return / exchange dispute', whatYouDo: 'Apply policy, escalate to store manager if customer pushes, do not argue on floor', howOften: 'weekly' },
  ],
});

const jewelleryShop = () => mk({
  role: 'Sales executive (Tamil Nadu jewellery showroom)',
  context: 'A regional jewellery chain branch — 22k gold, diamond, silver; high-trust, family decision purchases',
  outputName: 'a jewellery sale closed and the bill raised',
  officialVersion: 'Welcome → understand occasion → tray viewing → trial → price quote (gold rate × weight + making + GST) → negotiation → exchange / new → POS → packing → exit puja.',
  instanceAnchor: 'a wedding shopping family from Tirunelveli last Saturday',
  trigger: 'A family enters the showroom, often with grandmother in tow',
  steps: [
    S(1, { action: 'Welcome with water, seat the family in the right counter section', tool: 'Voice + showroom layout', inputSource: 'A client / customer', timeMins: 4, frequency: 'many-times-a-day', needsJudgment: true, notes: 'Decision-maker is rarely the loudest one — read the family first.' }),
    S(2, { action: 'Ask the occasion, budget range gently, weight preference, design family (antique / modern)', tool: 'Voice', timeMins: 5, frequency: 'many-times-a-day', needsJudgment: true }),
    S(3, { action: 'Pull 3–5 trays from the safe, lay out for viewing', tool: 'Trays + safe key', timeMins: 8, frequency: 'many-times-a-day', frictionTags: ['movement', 'lookup'] }),
    S(4, { action: 'Help trial — necklace fit, weight feel, mirror angle for the deciding aunt', tool: 'Mirror + clip', timeMins: 15, frequency: 'many-times-a-day', needsJudgment: true }),
    S(5, { action: 'Quote on the weighing scale + tag — gold rate today × weight + making + stone + GST', tool: 'Tag + scale + calculator + day rate board', outputWhat: 'a final price', timeMins: 6, frequency: 'many-times-a-day', frictionTags: ['lookup'], needsJudgment: true, notes: 'Gold rate changes daily; making is negotiable; that is the song.' }),
    S(6, { action: 'Negotiate — making charge waiver, ear stud free, exchange of old gold', tool: 'Voice + manager nod', frequency: 'many-times-a-day', needsJudgment: true, isPainful: true, notes: 'Bound by manager limits, but I read how far I can stretch.' }),
    S(7, { action: 'For exchange — weigh and assay old gold, deduct wastage, agree net value', tool: 'Weighing scale + assay touchstone', timeMins: 20, frequency: 'few-times-a-week', needsJudgment: true, isShadow: true, notes: 'Assay sometimes calls in the master — judgment + trust between us.' }),
    S(8, { action: 'POS billing — Aadhaar / PAN above ₹2 lakh, GST, scheme / coupon, payment method', tool: 'POS + KYC scanner', timeMins: 12, frequency: 'many-times-a-day', frictionTags: ['manual-transfer', 'wait'] }),
    S(9, { action: 'Engrave / personalise if requested; agree pickup date', tool: 'Engraving counter + job slip', outputDestination: 'Workshop', frequency: 'few-times-a-week', frictionTags: ['wait'] }),
    S(10, { action: 'Pack in branded velvet box, photo with family if they wish, walk to exit', tool: 'Velvet box + camera', outputDestination: 'A client / customer', timeMins: 6, frequency: 'many-times-a-day' }),
    S(11, { action: 'Log in my own register — what the family bought, what they considered, their wedding date', tool: 'Personal register', inputSource: 'My own notes', timeMins: 5, frequency: 'daily', isShadow: true, notes: 'Helps me call them for upcoming muhurthams. CRM does not track this nuance.' }),
  ],
  handoffs: [
    { direction: 'wait-on', who: 'Branch manager', what: 'discount approval beyond my limit', typicalDelay: 'minutes during browsing' },
    { direction: 'hand-to', who: 'Workshop', what: 'engraving / resize / repair job slip', typicalDelay: '2–7 days' },
  ],
  exceptions: [
    { trigger: 'Customer leaves without buying after long viewing', whatYouDo: 'Take number, send follow-up WhatsApp with photos that night, log in personal register', howOften: 'most days' },
    { trigger: 'Exchange dispute over wastage %', whatYouDo: 'Re-assay in front of customer, manager joins, settle within policy', howOften: 'weekly' },
  ],
});

const mobileShop = () => mk({
  role: 'Mobile phone shop owner-operator',
  context: 'A small smartphone + accessory shop on a Chennai high street; sells, repairs, takes EMI, deals in old exchange',
  outputName: 'a customer leaving with a working new or repaired phone',
  officialVersion: 'Walk-in → demo → quote → EMI / exchange / cash → activation → data transfer → bill → 7-day return guarantee.',
  instanceAnchor: 'a student upgrading to mid-range, exchange of old phone, last evening',
  trigger: 'Customer walks in asking to see phones in a price range',
  steps: [
    S(1, { action: 'Ask budget, brand preference, primary use (camera, gaming, family elder)', tool: 'Voice', inputSource: 'A client / customer', timeMins: 4, frequency: 'many-times-a-day', needsJudgment: true }),
    S(2, { action: 'Pull 2–3 phones for demo, explain real difference (not the spec sheet)', tool: 'Demo handsets', timeMins: 10, frequency: 'many-times-a-day', needsJudgment: true, isShadow: true, notes: 'I keep a mental map of which phones genuinely beat which at each price point — never on a sticker.' }),
    S(3, { action: 'Quote — sticker price, plus exchange estimate, plus EMI option (Bajaj / HDFC card)', tool: 'Calculator + EMI app + my own exchange chart', inputSource: 'My own notes', timeMins: 5, frequency: 'many-times-a-day', frictionTags: ['lookup'], needsJudgment: true }),
    S(4, { action: 'Inspect old phone for exchange — screen, battery health, scratches', tool: 'My eyes + diagnostic app', timeMins: 8, frequency: 'few-times-a-week', needsJudgment: true, notes: 'Underquote = lost sale; overquote = my loss when reselling.' }),
    S(5, { action: 'Apply for Bajaj / HDFC EMI on customer\'s phone OTP', tool: 'Bajaj merchant app + customer phone', timeMins: 12, frequency: 'few-times-a-week', frictionTags: ['wait'], notes: 'OTP delay is daily pain — sometimes 3 attempts.' }),
    S(6, { action: 'Pull new phone from drawer, unbox in front of customer, IMEI tally with box', tool: 'Stock drawer + IMEI scanner', timeMins: 5, frequency: 'many-times-a-day', frictionTags: ['lookup'] }),
    S(7, { action: 'Set up — SIM transfer, Google login, WhatsApp transfer from old to new, install basics', tool: 'Cables + SIM tools + transfer app', timeMins: 25, frequency: 'many-times-a-day', frictionTags: ['wait'], needsJudgment: true, isPainful: true, notes: 'WhatsApp transfer is the longest step — and the most cherished by the customer.' }),
    S(8, { action: 'Apply screen guard + back cover (free with most sales)', tool: 'Screen guard + cover', timeMins: 8, frequency: 'many-times-a-day' }),
    S(9, { action: 'Bill on POS / billing app, GST invoice, EMI papers signed', tool: 'Vyapar + EMI papers', outputDestination: 'A client / customer', timeMins: 6, frequency: 'many-times-a-day' }),
    S(10, { action: 'Log the old exchange phone into the old-stock notebook for resale tracking', tool: 'Old-stock notebook', inputSource: 'My own notes', outputWhat: 'a tracked resale unit', frequency: 'few-times-a-week', isShadow: true, frictionTags: ['manual-transfer'], notes: 'Personal notebook — no system tracks traded-in stock; a real ledger would.' }),
    S(11, { action: 'Decide repair vs flip vs scrap for the traded-in unit', tool: 'My eyes + resale-value judgment', inputSource: 'My own notes', frequency: 'few-times-a-week', needsJudgment: true, notes: 'Valuation call built from selling — what it fetches refurbished vs the repair cost.' }),
  ],
  handoffs: [
    { direction: 'wait-on', who: 'EMI bank server', what: 'EMI approval OTP', typicalDelay: 'minutes' },
    { direction: 'hand-to', who: 'Repair technician (back room)', what: 'units to be repaired or refurbished', typicalDelay: '1–3 days' },
  ],
  exceptions: [
    { trigger: 'EMI declined for customer', whatYouDo: 'Offer alternate bank, downsell to lower model, or save customer info for next time', howOften: 'daily' },
    { trigger: 'Customer returns within 7 days claiming defect', whatYouDo: 'Test in front of them, if real issue escalate to brand service, otherwise polite no', howOften: 'weekly' },
  ],
});

const supermarketCashier = () => mk({
  role: 'Supermarket cashier (modern trade outlet)',
  context: 'A Nilgiris / Reliance Fresh / DMart-style cashier counter at a Chennai branch',
  outputName: 'a customer billed and out the door with their trolley',
  officialVersion: 'Scan → totalise → loyalty → tender → bag → exit greeting; lane drawer reconciled at end of shift.',
  instanceAnchor: 'a Sunday evening rush with full trolleys',
  trigger: 'A customer rolls a trolley onto my belt',
  steps: [
    S(1, { action: 'Greet, start scanning items off the belt', tool: 'POS + barcode scanner', inputSource: 'A client / customer', timeMins: 5, frequency: 'many-times-a-day' }),
    S(2, { action: 'Weigh and key in PLU for loose veg / fruit that has no barcode', tool: 'Counter scale + PLU sheet', timeMins: 3, frequency: 'many-times-a-day', frictionTags: ['lookup'], needsJudgment: true, notes: 'PLU sheet is laminated — but I know top 30 by heart.' }),
    S(3, { action: 'Handle the "no barcode" / "this was on offer" objection mid-scan', tool: 'Voice + price-check intercom', frequency: 'many-times-a-day', frictionTags: ['wait', 'chasing'], notes: 'Either call a floor associate to check or do it off the shelf in my head.' }),
    S(4, { action: 'Ask for loyalty number, apply offers and coupons', tool: 'POS loyalty screen', timeMins: 2, frequency: 'many-times-a-day' }),
    S(5, { action: 'Take payment — UPI scan, card swipe, cash; handle change', tool: 'POS + UPI QR + EDC + cash drawer', timeMins: 3, frequency: 'many-times-a-day', frictionTags: ['wait'] }),
    S(6, { action: 'Pack into branded bags or customer\'s own bag', tool: 'Carry bag', outputDestination: 'A client / customer', timeMins: 3, frequency: 'many-times-a-day' }),
    S(7, { action: 'Print bill, staple sticker on bag, exit greeting', tool: 'POS printer', timeMins: 1, frequency: 'many-times-a-day' }),
    S(8, { action: 'Quick scan of the next customer\'s trolley to set expectation', tool: 'Eyes', frequency: 'many-times-a-day', isShadow: true, needsJudgment: true, notes: 'Pre-judge tender type and total — speeds the next billing.' }),
    S(9, { action: 'EOD drawer reconciliation + EDC settlement + UPI tally', tool: 'POS report + drawer count', timeMins: 25, frequency: 'daily', frictionTags: ['manual-transfer'], isPainful: true, notes: 'Short or over = hold the shift, find it before I leave.' }),
  ],
  handoffs: [
    { direction: 'wait-on', who: 'Floor associate', what: 'price check / replacement on a flagged item', typicalDelay: '1–3 min — feels longer with a queue' },
    { direction: 'hand-to', who: 'Cash office', what: 'reconciled drawer at EOD', typicalDelay: 'shift end' },
  ],
  exceptions: [
    { trigger: 'POS hangs mid-bill', whatYouDo: 'Hold queue, call IT helpdesk, switch to manual bill book for the next 4–5 customers', howOften: 'weekly' },
    { trigger: 'Cash short at EOD', whatYouDo: 'Recount, replay top transactions in head, escalate to supervisor; difference docked over week', howOften: 'monthly' },
  ],
});

export const RETAIL: WorkedExample[] = [
  { key: 'medical-shop', label: 'A retail chemist reading a prescription', domain: 'Retail', region: 'Tamil Nadu', emoji: '💊',
    summary: 'Deciphering doctor scrawl, a statutory Schedule-H register kept by hand, and chronic patients on a pension-day credit ledger.',
    behavioralContext: 'The capture marks prescription-reading as the painful, error-prone step and the chronic-patient credit as a shadow trust account. The hand-written Schedule-H register is a compliance duty re-keyed beside the bill — friction, but a legal one that can\'t simply be deleted.',
    fieldSpecificFit: 'Leave the substitution judgment and the credit relationship with the pharmacist. The trace points the tool at two seams: a digital Schedule-H log that fills from the bill (ending the double entry) and an expiry/low-stock reorder alert. Prescription-reading stays human, with a phone-the-clinic fallback for the scary cases.',
    build: medicalShop },
  { key: 'hardware-store', label: 'A hardware shop fulfilling a contractor list', domain: 'Retail', region: 'Tamil Nadu', emoji: '🔩',
    summary: 'Loose contractor-speak translated to exact SKUs, prices and credit held by relationship, month-end khata reconciliation the dreaded chore.',
    behavioralContext: 'The capture tags khata pricing as a shadow judgment (rate + credit by relationship, not a tag) and month-end reconciliation as the painful step. The remembered contractor rates are the loyalty that keeps the account — a rigid catalogue price would lose it.',
    fieldSpecificFit: 'The fit the trace supports is the back-office, not the counter banter: a running per-contractor ledger that logs each khata entry and produces a clean month-end statement, plus stock visibility for the godown hunt. The spec advice and relationship pricing stay the owner\'s.',
    build: hardwareStore },
  { key: 'saree-showroom', label: 'A saree showroom closing a wedding family', domain: 'Retail', region: 'Tamil Nadu', emoji: '🥻',
    summary: 'Twenty sarees pulled for two sold, each family member\'s shortlist tracked in the head, then invisible refold-and-restock after every sit.',
    behavioralContext: 'The capture marks the physical pull-and-show as the painful step, shortlist-tracking as a shadow judgment, and the refold/restock as invisible reset work that the sales sheet never credits. The occasion-reading is taste and status fluency no recommender replaces.',
    fieldSpecificFit: 'Don\'t touch the consultative selling — that taste is the sale. The trace points the tool at the seams: a tablet shortlist that holds each member\'s picks and pushes straight to billing (collapsing the slip + double-queue), and stock-location lookup to cut the pulling. Restock effort finally becomes visible.',
    build: sareeShowroom },
  { key: 'kirana-store', label: 'A day at the neighbourhood kirana', domain: 'Retail', region: 'Chennai, TN', emoji: '🏪',
    summary: 'A kirana owner between Vyapar, a credit notebook and a UPI QR — three sources of truth that have to add up every night.',
    behavioralContext: 'The trace tags the credit notebook (paavu) as both shadow work and a judgment step — who gets udhaar and for how long is the owner\'s social read, and it is the moat against Zepto. A rule-based "credit manager" would break the very trust that keeps the lane loyal.',
    fieldSpecificFit: 'The step the capture marks painful is the nightly three-way tally, not the credit call. Auto-reconcile UPI history + cash drawer + the day\'s bills into one figure and flag only the mismatch; leave the credit book in the owner\'s hand. Automate the arithmetic, keep the relationship human.',
    build: kiranaStore },
  { key: 'petrol-pump', label: 'Closing a petrol pump shift', domain: 'Retail', region: 'Chennai, TN', emoji: '⛽',
    summary: 'A pump attendant between totaliser readings, dip rods, card terminals and a cash bag — short = own pocket, so the reconciliation is sacred.',
    behavioralContext: 'Because a shortfall comes out of the attendant\'s own pocket, the trace shows the retrace tagged as judgment + rework done by hand on purpose — they trust their own re-count. A system that just asserts "you are short ₹40" without showing where erodes that trust instantly.',
    fieldSpecificFit: 'Pull totaliser, EDC settlement and UPI into one expected-vs-actual sheet that shows the working — and auto-flags the culprits the trace already names (double-swipe, a missing fleet slip). The attendant still owns the close the capture marks sacred; the tool just removes the manual cross-adding.',
    build: petrolPump },
  { key: 'mall-fashion', label: 'Mall fashion floor — Sunday rush', domain: 'Retail', region: 'India urban', emoji: '👕',
    summary: 'A sales associate reading customers, suggesting add-ons, racing a basket-size commission target and logging lost-sale reasons in a personal notebook.',
    behavioralContext: 'The capture shows the edge living in two shadow steps: the floor-read (judgment) and tracking new arrivals by what they personally hung that morning — neither in the SKU-based POS. The lost-sale notebook is kept private because HQ\'s weekly form reads like surveillance, so a sanitised copy goes up.',
    fieldSpecificFit: 'Kill the double-entry the trace exposes, not the notebook: log lost-sale reasons once (voice / quick-tap on their own device) and roll them up to HQ automatically. Give them a today\'s-arrivals view tied to what physically came in, turning that private morning-hang memory into a shared signal.',
    build: mallFashion },
  { key: 'jewellery-shop', label: 'TN jewellery showroom — a wedding family', domain: 'Retail', region: 'Tamil Nadu', emoji: '💍',
    summary: 'A jewellery executive between trays, assay touchstone, daily gold rate, exchange wastage and a personal register of family wedding dates.',
    behavioralContext: 'The trace marks the personal register of muhurthams and who-decides as relationship capital the CRM cannot hold, and the exchange assay as a judgment step run on trust between executive and master. A CRM that demands every family detail be logged is read as the chain trying to own the executive\'s clients.',
    fieldSpecificFit: 'A private follow-up workspace the executive owns — reminding them of logged wedding dates and storing the photos they already WhatsApp — beats a corporate CRM. For the assay step the capture flags as shared judgment, a co-signed assay-record screen makes the trust auditable without removing the human call.',
    build: jewelleryShop },
  { key: 'mobile-shop', label: 'Selling a smartphone with exchange + EMI', domain: 'Retail', region: 'Chennai, TN', emoji: '📱',
    summary: 'A high-street mobile shop owner doing exchange valuation, Bajaj EMI OTP dance, and the longest step of all — the WhatsApp transfer from old phone to new.',
    behavioralContext: 'The trace tags the "which phone actually beats which" demo and the exchange quote as judgment built from selling, not spec sheets — that honesty is why customers return. The WhatsApp transfer, though the longest step, is marked as the one the customer cherishes most, so it is not waste to be cut.',
    fieldSpecificFit: 'Do not automate the advice or the cherished transfer ritual. Target the steps the capture flags as friction: the Bajaj/HDFC EMI OTP retries (a faster pre-checked flow) and the old-stock tracking (a simple flip/repair/scrap ledger for traded-in units). The valuation call itself stays the owner\'s judgment.',
    build: mobileShop },
  { key: 'supermarket-cashier', label: 'Modern-trade cashier at Sunday peak', domain: 'Retail', region: 'India urban', emoji: '🛒',
    summary: 'A cashier scanning, weighing, applying loyalty and bagging — short drawer at EOD = stay back till it adds up.',
    behavioralContext: 'The capture surfaces two shadow steps behind the speed — memorised top-30 PLUs and pre-reading the next trolley\'s tender — that the POS never sees. The EOD reconcile is tagged painful because the shortfall is personal, so a black-box "you are short" would land as an accusation.',
    fieldSpecificFit: 'Two narrow fixes the trace points to: a lane-side price-check for the "it was on offer" objection (no paging a floor associate) and an EOD reconcile that shows the transaction trail behind any mismatch. The memorised-PLU speed is an asset — surface a smarter PLU shortlist, do not replace the muscle memory.',
    build: supermarketCashier },
];
